// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtvqgyrhriilctqdoenj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0dnFneXJocmlpbGN0cWRvZW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NzQ1NjEsImV4cCI6MjA2MzI1MDU2MX0.8GvBvmPJw0MHGs3Jd4_rOgXliRYS0YRfG8lkMZaUlJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);